name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: postgres
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://docker:docker@localhost:5432/postgres?schema=public
      DATABASE_USER: docker
      DATABASE_PASSWORD: docker
      DATABASE_NAME: postgres
      DATABASE_PORT: "5432"
      SENTRY_DSN: test-sentry
      REDIS_HOST: localhost
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - run: npm run db:deploy

      - run: npm run test:e2e
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/postgres?schema=public"
